//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRKAdminCore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LDEntities : DbContext
    {
        public LDEntities()
            : base("name=LDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LD30Attribute> LD30Attribute { get; set; }
        public virtual DbSet<LD30LinkedAttribute> LD30LinkedAttribute { get; set; }
        public virtual DbSet<LD3Method> LD3Method { get; set; }
        public virtual DbSet<LD3Overlay> LD3Overlay { get; set; }
        public virtual DbSet<LDCOLUMN> LDCOLUMN { get; set; }
        public virtual DbSet<LDCOLUMNLINK> LDCOLUMNLINK { get; set; }
        public virtual DbSet<LDOBJECTTYPE> LDOBJECTTYPE { get; set; }
        public virtual DbSet<LDTABLE> LDTABLE { get; set; }
        public virtual DbSet<LDTABLELINK> LDTABLELINK { get; set; }
    }
}
