//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRKAdminCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD30LinkedAttribute
    {
        public int AttributeID { get; set; }
        public Nullable<int> TableLinkID { get; set; }
        public Nullable<int> ColumnLinkID { get; set; }
        public int ToColumnID { get; set; }
    
        public virtual LD30Attribute LD30Attribute { get; set; }
        public virtual LDTABLELINK LDTABLELINK { get; set; }
    }
}
