//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRKAdminCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LD3Overlay
    {
        public int ObjectTypeID { get; set; }
        public string AttributeName { get; set; }
        public string DisplayLabel { get; set; }
        public int VisibleIndex { get; set; }
    
        public virtual LDOBJECTTYPE LDOBJECTTYPE { get; set; }
    }
}
