//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRKAdminCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDCOLUMNLINK
    {
        public int TableLinkID { get; set; }
        public int FromColumnID { get; set; }
        public int ToColumnID { get; set; }
    }
}
