//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRKAdminCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDCOLUMN
    {
        public int ID { get; set; }
        public int TableID { get; set; }
        public int DataTypeID { get; set; }
        public Nullable<int> ViewColumnID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Length { get; set; }
        public string PKey { get; set; }
        public int Alignment { get; set; }
        public string DisplayLabel { get; set; }
        public string GUIField { get; set; }
        public string InfoField { get; set; }
        public string NotNull { get; set; }
        public string ResField { get; set; }
        public string SortFields { get; set; }
        public Nullable<int> ControlTypeID { get; set; }
        public Nullable<int> RefObjectTypeID { get; set; }
        public string Deleted { get; set; }
        public string FullDisplayLabel { get; set; }
        public string UseLastVersion { get; set; }
        public string Grouping { get; set; }
        public string DualListVisible { get; set; }
        public string LinkResField { get; set; }
    
        public virtual LDOBJECTTYPE LDOBJECTTYPE { get; set; }
    }
}
