//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRKAdminCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDOBJECTTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LDOBJECTTYPE()
        {
            this.LD3Method = new HashSet<LD3Method>();
            this.LD3Overlay = new HashSet<LD3Overlay>();
            this.LDCOLUMN = new HashSet<LDCOLUMN>();
            this.LDOBJECTTYPE1 = new HashSet<LDOBJECTTYPE>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string DisplayLabel { get; set; }
        public Nullable<int> AccessMode { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string System { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> ViewTableID { get; set; }
        public string ResName { get; set; }
        public Nullable<int> VersionESign { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> ObjTpCategoryID { get; set; }
        public Nullable<int> AddFormID { get; set; }
        public System.Guid UID { get; set; }
        public string VersionAllow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LD3Method> LD3Method { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LD3Overlay> LD3Overlay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LDCOLUMN> LDCOLUMN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LDOBJECTTYPE> LDOBJECTTYPE1 { get; set; }
        public virtual LDOBJECTTYPE LDOBJECTTYPE2 { get; set; }
        public virtual LDTABLE LDTABLE { get; set; }
        public virtual LDTABLE LDTABLE1 { get; set; }
    }
}
