//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRKAdminCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDTABLELINK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LDTABLELINK()
        {
            this.LD30LinkedAttribute = new HashSet<LD30LinkedAttribute>();
        }
    
        public int ID { get; set; }
        public int FromTableID { get; set; }
        public int ToTableID { get; set; }
        public Nullable<int> Type { get; set; }
        public string GUILink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LD30LinkedAttribute> LD30LinkedAttribute { get; set; }
    }
}
